version: '3.7'
services:
  db:
    build: 
      context: ./MySQL
      dockerfile: Dockerfile
    container_name: mysql_exam2
    restart: always
    ports:
      - 4800:3306
    volumes:
      - ./Config/mysql:/var/lib/mysql
    hostname: apps_database2
    networks:
      - exam2_apps
    healthcheck:
        test: ["CMD","mysql", "-u", "root", "-p2210"]
        interval: 30s
        timeout: 10s
        retries: 5
# --------------------------------------------------------------------
  # - The adminer is a tool for managing content in databases.
  adminer:
    image: adminer
    container_name: adminer_wms2
    restart: always
    ports:
      - 9001:8080
    networks:
      - exam2_apps
# --------------------------------------------------------------------

networks:
  exam2_apps:
      driver: bridge
      name: exam2_apps